name: Run pre-commit
description: Run pre-commit

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "1"
    - name: set PY
      shell: bash -el {0}
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - name: "Install pre-commit"
      shell: bash -el {0}
      run: pipx install pre-commit
    - uses: actions/cache/restore@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      id: cache
    - if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: "Run pre-commit"
      shell: bash -e {0}
      run: |
        echo '```console' > $GITHUB_STEP_SUMMARY
        # Enable color output for pre-commit and remove it for the summary
        pre-commit run --all-files --show-diff-on-failure --color=always | \
          tee >(sed -E 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?[mGK]//g' >> $GITHUB_STEP_SUMMARY) >&1
        exit_code=${PIPESTATUS[0]}
        echo '```' >> $GITHUB_STEP_SUMMARY
        exit $exit_code
