name: prek
description: Run prek

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: "1"
        filter: "blob:none"
        persist-credentials: false
    - name: Install prek
      shell: bash -e {0}
      run: pipx install prek
    - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ~/.cache/prek
        key: prek|${{ hashFiles('.pre-commit-config.yaml') }}
      id: cache
    - name: Run prek
      shell: bash {0}
      run: |
        prek run --all-files --show-diff-on-failure --color=always | tee /tmp/prek.log >&1
        exit_code=${PIPESTATUS[0]}

        echo '```console' > $GITHUB_STEP_SUMMARY
        sed -E 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?[mGK]//g' /tmp/prek.log >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

        exit $exit_code
    - if: always() && steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ~/.cache/prek
        key: prek|${{ hashFiles('.pre-commit-config.yaml') }}
