name: Pixi lock
description: Get or create the pixi.lock
inputs:
  cache:
    description: Whether to enable caching of the lock-file
    required: true
    default: "true"
  pixi-version:
    description: The version of pixi to use
    required: false
  pixi-manifest-path:
    description: The path to the pixi manifest file
    required: false

runs:
  using: "composite"
  steps:
    - name: Set TODAY
      id: set-today
      shell: bash -e {0}
      run: |
        echo "TODAY=$(command date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: "1"
        persist-credentials: false
    - if: inputs.cache == 'true'
      id: cache
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: pixi.lock
        key: pixi|${{ steps.set-today.outputs.TODAY }}|${{ hashFiles('pixi.toml') }}
    - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        pixi-version: ${{ inputs.pixi-version }}
        manifest-path: ${{ inputs.pixi-manifest-path }}
        run-install: false
    - name: Lock
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash -e {0}
      run: |
        echo "::group::Lock"
        pixi lock --color=always
        echo "::endgroup::"
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: pixi-lock
        path: pixi.lock
        if-no-files-found: error
    - if: inputs.cache == 'true' && steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: pixi.lock
        key: pixi|${{ steps.set-today.outputs.TODAY }}|${{ hashFiles('pixi.toml') }}
