name: Publish documentation
description: Publish docs to AWS
inputs:
  s3-url:
    description: The URL to the S3 bucket, no trailing slash.
    required: true
  s3-access-key-id:
    description: Access key ID to use for S3 authentication.
    required: true
  s3-secret-access-key:
    description: Secret access key to use for S3 authentication.
    required: true
  s3-cloudfront-id:
    description: The S3 cloudfront id.
    required: true
  version:
    description: The version (only if target is main).
    required: true
  build-path:
    description: The directory to upload.
    default: ./builtdocs/
  switcher-path:
    description: The path to the switcher.json file.
    default: ./builtdocs/_static/switcher.json
  sitemap-path:
    description: The path to the sitemap.xml file.
    default: ./docs/_nbsite_versioned/sitemap.xml
  robots-path:
    description: The path to the robots.txt file.
    default: ./docs/_nbsite_versioned/robots.txt

runs:
  using: "composite"
  steps:
    - shell: bash -e {0}
      id: vars
      run: |
        echo "Deploying from ref: ${GITHUB_REF#refs/*/}"
        echo "tag=${GITHUB_REF#refs/*/}" > $GITHUB_OUTPUT
    - name: dev
      shell: bash -e {0}
      if: |
        (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'dev') ||
        (github.event_name == 'push' && (contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc')))
      env:
        YEAR_CACHE: "31536000" # 3600 * 24 * 365
        BUILD_PATH: "${{ inputs.build-path }}"
        S3_URL: "${{ inputs.s3-url }}"
        S3_CLOUDFRONT_ID: "${{ inputs.s3-cloudfront-id }}"
        AWS_ACCESS_KEY_ID: ${{ inputs.s3-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.s3-secret-access-key }}
      run: |
        # Upload dev
        echo "::group::Upload dev"
        aws s3 sync --delete "$BUILD_PATH" "$S3_URL/en/docs/dev/" --cache-control max-age=$YEAR_CACHE,public
        echo "::endgroup::"
        echo "::group::Invalidate cloudfront"
        aws cloudfront create-invalidation --distribution-id "$S3_CLOUDFRONT_ID" --paths "/en/docs/dev*"
        echo "::endgroup::"
    - name: main
      shell: bash -e {0}
      if: |
        (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'main') ||
        (github.event_name == 'push' && !(contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc')))
      env:
        WEEK_CACHE: "604800" # 3600 * 24 * 7
        YEAR_CACHE: "31536000" # 3600 * 24 * 365
        BUILD_PATH: "${{ inputs.build-path }}"
        SWITCHER_PATH: "${{ inputs.switcher-path }}"
        SITEMAP_PATH: "${{ inputs.sitemap-path }}"
        ROBOTS_PATH: "${{ inputs.robots-path }}"
        S3_URL: "${{ inputs.s3-url }}"
        S3_CLOUDFRONT_ID: "${{ inputs.s3-cloudfront-id }}"
        AWS_ACCESS_KEY_ID: ${{ inputs.s3-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.s3-secret-access-key }}
        INPUT_VERSION: "${{ inputs.version }}"
        TAG_VERSION: "${{ steps.vars.outputs.tag }}"
        GH_EVENT_NAME: "${{ github.event_name }}"
      run: |
        # Upload main
        if [ "$GH_EVENT_NAME" = "workflow_dispatch" ]; then
          VERSION="$INPUT_VERSION"
        else
          VERSION="$TAG_VERSION"
        fi
        # Remove s3://
        BUCKET_NAME="${S3_URL:5}"
        echo "::group::Upload latest"
        aws s3 sync --delete "$BUILD_PATH" "$S3_URL/en/docs/latest/" --cache-control max-age=$WEEK_CACHE,public
        echo "::endgroup::"
        echo "::group::Upload $VERSION"
        aws s3 sync --delete "$BUILD_PATH" "$S3_URL/en/docs/$VERSION/" --cache-control max-age=$YEAR_CACHE,public
        echo "::endgroup::"
        echo "::group::Copy switcher.json"
        aws s3 cp "$SWITCHER_PATH" "$S3_URL" --cache-control max-age=$WEEK_CACHE,public
        echo "::endgroup::"
        echo "::group::Copy sitemap.xml"
        aws s3 cp "$SITEMAP_PATH" "$S3_URL" --cache-control max-age=$WEEK_CACHE,public
        echo "::endgroup::"
        echo "::group::Copy robots.txt"
        aws s3 cp "$ROBOTS_PATH" "$S3_URL" --cache-control max-age=$WEEK_CACHE,public
        echo "::endgroup::"
        echo "::group::Invoke site-directory-manifest lambda"
        aws lambda invoke --function-name site-directory-manifest --payload "{\"bucket":\"$BUCKET_NAME\"}" response.json
        echo "::endgroup::"
        echo "::group::Invalidate cloudfront"
        aws cloudfront create-invalidation --distribution-id "$S3_CLOUDFRONT_ID" --paths "/en/docs/latest*" "/en/docs/$VERSION*" "/switcher.json" "/sitemap.xml" "/robots.txt"
        echo "::endgroup::"
    - name: dryrun
      shell: bash -e {0}
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'dryrun'
      env:
        BUILD_PATH: "${{ inputs.build-path }}"
        S3_URL: "${{ inputs.s3-url }}"
        AWS_ACCESS_KEY_ID: ${{ inputs.s3-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.s3-secret-access-key }}
      run: |
        # Dryrun
        echo "::group::Dryrun"
        aws s3 sync --delete --dryrun "$BUILD_PATH" "$S3_URL/en/docs/latest/"
        echo "::endgroup::"
