name: Docs publish
description: Publish docs to AWS
inputs:
  url:
    description: The URL to the S3 bucket, no trailing slash
    required: true
  cloudfront_id:
    description: The cloudfront id
    required: true
  version:
    description: The version (only if target is main)
    required: true
  build_path:
    description: The directory to upload
    default: ./builtdocs/
  switcher_path:
    description: The path to the switcher.json relative to the build_path
    default: _static/switcher.json

runs:
  using: "composite"
  steps:
    - shell: bash -e {0}
      id: vars
      run: |
        echo "Deploying from ref: ${GITHUB_REF#refs/*/}"
        echo "tag=${GITHUB_REF#refs/*/}" > $GITHUB_OUTPUT
    - name: dev
      shell: bash -e {0}
      if: |
        (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'dev') ||
        (github.event_name == 'push' && (contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc')))
      env:
        WEEK_CACHE: "315360" # 3600 * 24 * 7
        BUILD_PATH: "${{ inputs.build_path }}"
        S3_URL: "${{ inputs.url }}"
        CLOUDFRONT_ID: "${{ inputs.cloudfront_id }}"
      run: |
        echo "::group::Upload dev"
        aws s3 sync --delete "$BUILD_PATH" "$S3_URL/en/docs/dev/" --cache-control max-age=$YEAR_CACHE,public
        aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_ID" --paths "/en/docs/dev*"
        echo "::endgroup::"
    - name: main
      shell: bash -e {0}
      if: |
        (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'main') ||
        (github.event_name == 'push' && !(contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc')))
      env:
        WEEK_CACHE: "315360" # 3600 * 24 * 7
        YEAR_CACHE: "31536000" # 3600 * 24 * 365
        BUILD_PATH: "${{ inputs.build_path }}"
        SWITCHER_PATH: "${{ inputs.switcher_path }}"
        S3_URL: "${{ inputs.url }}"
        CLOUDFRONT_ID: "${{ inputs.cloudfront_id }}"
        VERSION: "${{ inputs.version }}"
      run: |
        echo "::group::Upload main"
        aws s3 sync --delete "$BUILD_PATH" "$S3_URL/en/docs/latest/" --cache-control max-age=$WEEK_CACHE,public
        aws s3 sync --delete "$BUILD_PATH" "$S3_URL/en/docs/$VERSION/" --cache-control max-age=$YEAR_CACHE,public
        aws s3 cp "$BUILD_PATH$SWITCHER_PATH" "$S3_URL" --cache-control max-age=$WEEK_CACHE,public
        aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_ID" --paths "/en/docs/latest*" "/en/docs/$VERSION*" "/switcher.json"
        echo "::endgroup::"
    - name: dryrun
      shell: bash -e {0}
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'dryrun'
      env:
        BUILD_PATH: "${{ inputs.build_path }}"
        S3_URL: "${{ inputs.url }}"
      run: |
        echo "::group::Dryrun"
        aws s3 sync --delete --dryrun "$BUILD_PATH" "$S3_URL/en/docs/latest/"
        echo "::endgroup::"
