name: PNG Optimize
description: Optimize PNG
inputs:
  oxipng-version:
    description: Version of oxipng to install
    required: false
    default: "8.0.0"
  token:
    description: GitHub token for pushing optimized images
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: "1"
        persist-credentials: false
        ref: ${{ github.head_ref || github.ref }}
    - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ~/.cargo/bin/oxipng
        key: oxipng|${{ runner.os }}|${{ inputs.oxipng-version }}
      id: cache
    - name: install
      shell: bash -e {0}
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        OXIPNG_VERSION: ${{ inputs.oxipng-version }}
      run: cargo install oxipng@=$OXIPNG_VERSION
    - name: run
      shell: bash -e {0}
      run: oxipng $(git ls-files "*.png")
    - name: check
      shell: bash -e {0}
      id: check
      run: |
        if [[ -n $(git status --porcelain "*.png") ]]; then
          echo "Images optimized, changes detected."
          echo "img_change=true" >> $GITHUB_OUTPUT
        else
          echo "No changes detected after optimization."
          echo "img_change=false" >> $GITHUB_OUTPUT
        fi
    - name: commit
      shell: bash -e {0}
      if: steps.check.outputs.img_change == 'true'
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        # Config
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"

        # Commit and push
        git add "*.png"
        git commit -m "Optimize PNG images (lossless)"
        git push origin

        # Reopen PR to trigger CI
        gh pr close "$PR_NUMBER"
        gh pr reopen "$PR_NUMBER"
    - if: always() && steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ~/.cargo/bin/oxipng
        key: oxipng|${{ runner.os }}|${{ inputs.oxipng-version }}
