name: Pixi Install
description: Setup Pixi environment
inputs:
  environments:
    description: environments to install
    required: true
  download-data:
    description: download data
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: "100"
    - name: Fetching tags
      shell: bash -el {0}
      run: |
        echo "::group::Fetching tags"
        git fetch --prune --tags -f
        echo "::endgroup::"
    - uses: actions/download-artifact@v4
      with:  # TODO: just ignore this if it does not exists
        name: pixi-lock
        path: .
    - uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: v0.19.0  # TODO: make this an input
        manifest-path: pixi.toml # TODO: make this an input
        environments: ${{ inputs.environments }}
        cache: false  # Cache is slower than downloading!
    - name: Download data
      if: ${{ inputs.download-data }}
      shell: bash -el {0}
      run: |
        echo "::group::Download data"
        # INFO: Does not really work with environments as it can be multiple but good enough
        pixi run -e ${{ inputs.environments }} download-data || echo "No data to download"
        echo "::endgroup::"
