name: Pixi Install
description: Setup Pixi environment
inputs:
  environments:
    description: environments to install
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: "100"
    - name: Fetch
      shell: bash -el {0}
      run: git fetch --prune --tags -f
    - uses: actions/download-artifact@v4
      with:
        name: pixi-lock
        path: .
    - uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: v0.19.0  # TODO: make this a input
        manifest-path: pixi.toml # TODO: make this a input
        environments: ${{ inputs.environments}}
        cache: false  # Cache is slower than downloading!
