name: Pixi lock
description: Get or create the pixi.lock
inputs:
  cache:
    description: Whether to enable caching of the lock-file
    required: true
    default: "true"
  pixi-version:
    description: The version of pixi to use
    required: false
  pixi-manifest-path:
    description: The path to the pixi manifest file
    required: false

runs:
  using: "composite"
  steps:
    - name: Set TODAY
      shell: bash -e {0}
      run: |
        echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - uses: actions/checkout@v4
      with:
        fetch-depth: "1"
    - if: inputs.cache == 'true'
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: pixi.lock
        key: pixi|${{ env.TODAY }}|${{ hashFiles('pixi.toml') }}
    - uses: prefix-dev/setup-pixi@v0.8.1
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        pixi-version: ${{ inputs.pixi-version }}
        manifest-path: ${{ inputs.pixi-manifest-path }}
        run-install: false
    - name: Run update  # Using `pixi update` so we don't need to create and download the default environment.
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash -e {0}
      run: |
        echo "::group::Update"
        pixi update
        echo "::endgroup::"
    - uses: actions/upload-artifact@v4
      with:
        name: pixi-lock
        path: pixi.lock
        if-no-files-found: error
    - if: inputs.cache == 'true' && steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: pixi.lock
        key: pixi|${{ env.TODAY }}|${{ hashFiles('pixi.toml') }}
