name: run_downstream_tests

on:
  workflow_call:
    inputs:
      downstream_repos_as_json:
        description: 'A JSON string of downstream repos to test'
        required: true
        type: string
      client_payload:
        description: 'A JSON string of client payload to pass to downstream tests'
        default: '{"target": "downstream", "cache": false}'
        required: false
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      downstream_repos_as_json:
        description: 'A JSON string of downstream repos to test'
        required: true
        type: string
      client_payload:
        description: 'A JSON string of client payload to pass to downstream tests'
        default: '{"target": "downstream", "cache": false}'
        required: false
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  UPSTREAM_REPO: ${{ github.event.repository.name }}

jobs:
  check_if_new_version_available:
    name: Check if new version available on pyviz/label/dev
    runs-on: ubuntu-latest
    # Run only if the caller workflow has completed with success,
    # or if it has a `manual` input set to true.
    if: ${{ (github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success') || github.event.inputs.manual == 'true' || github.event_name == 'workflow_dispatch' }}
    timeout-minutes: 10
    steps:
    - name: Print event data
      env:
        EVENT: ${{ toJSON( github.event ) }}
      run: echo "$EVENT"
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      name: Checkout repo
      with:
        fetch-depth: "1"
        persist-credentials: false
    - name: Fetch tags
      run: git fetch --tags
    - name: Git Tag
      id: from_git
      run: |
        echo "version=$(git tag -l --sort=-creatordate | head -n 1 | cut -c 2-)" >> $GITHUB_OUTPUT
    - name: Conda Version
      id: from_conda
      env:
        PACKAGE: ${{ env.UPSTREAM_REPO }}
        GIT_VERSION: ${{ steps.from_git.outputs.version }}
      run: |
        # Use the anaconda.org API to check if the version is available on pyviz.
        # If it's not available then version will be set to null, otherwise
        # it'll be set to the version found in the metadata, i.e. 1.12.1a1.
        echo "version=$(curl -s "https://api.anaconda.org/release/pyviz/${PACKAGE}/${GIT_VERSION}" | jq -r '.distributions[0].version // "null"')" >> $GITHUB_OUTPUT
    - name: Print git tag and conda version found
      env:
        GIT_VERSION: ${{ steps.from_git.outputs.version }}
        CONDA_VERSION: ${{ steps.from_conda.outputs.version }}
      run: |
        echo "Git Tag:       $GIT_VERSION"
        echo "Conda Version: $CONDA_VERSION"
    - name: Stop if git tag and conda version are different
      if: ${{ steps.from_git.outputs.version != steps.from_conda.outputs.version && github.event_name != 'workflow_dispatch' }}
      run: exit 1

  downstream_tests:
    name: Run downstream tests
    needs: check_if_new_version_available
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(inputs.downstream_repos_as_json) }}
      fail-fast: false
    timeout-minutes: 240
    steps:
    - name: Trigger downstream test workflow and wait
      uses: convictional/trigger-workflow-and-wait@f69fa9eedd3c62a599220f4d5745230e237904be # v1.6.5
      with:
        owner: holoviz
        repo: ${{ matrix.downstream_repo }}
        github_token: ${{ secrets.ACCESS_TOKEN }}
        workflow_file_name: test.yaml
        client_payload: ${{ inputs.client_payload }}
        ref: main
        wait_interval: 120
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
