name: Update major tag

on:
  push:
    tags:
      - "v*.*.*"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update-major-tag:
    name: Update major tag
    runs-on: ubuntu-latest
    permissions:
      contents: write # OK
    steps:
      - name: Checkout repo # zizmor: ignore[artipacked]
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: "1"
      - name: Update major tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          TAG="${GITHUB_REF_NAME}"
          MAJOR=$(echo "$TAG" | cut -d. -f1)

          git tag -f "${MAJOR}" "${TAG}"
          git push origin "${MAJOR}" --force
